### ISSUE TITLE
F429 entropy

### ISSUE THREAD

**Issue by markus-becker-tridonic-com** [ARMmbed/target-st-stm32f429i-disco#16] opened 2015-10-08 09:46 UTC
Otherwise cmsis-core is not always pulled in.

The K64F target specifies "mbed" in "similarTo".

**Comment by 0xc0170** [comment] 2015-10-08 09:49
Can you be more specific? I can't find it in k64f, for example armcc: https://github.com/ARMmbed/target-frdm-k64f-armcc/blob/master/target.json#L78 . Because similarTo "mbed" is set in mbed targets (https://github.com/ARMmbed/target-mbed-armcc/blob/master/target.json#L23)

Where is cmsis-core not pulled it?

**Comment by markus-becker-tridonic-com** [comment] 2015-10-08 09:55
At least the gcc target is having it: https://github.com/ARMmbed/target-frdm-k64f-gcc/blob/master/target.json#L93

We had problems with the F429 with the 6lowpan-example complaining about not finding cmsis.h.

Adding "mbed" to the similarTo solved it for us.

**Comment by rainierwolfcastle** [comment] 2015-10-15 15:03
http://jira-dev0.cambridge.arm.com/browse/IOTSFW-829

**Comment by rainierwolfcastle** [comment] 2015-10-16 15:39
ARM Internal Ref: IOTSFW-985

**Comment by 0xc0170** [comment] 2015-11-09 07:57
> When you create a new target that's based on an existing target, you should copy its similarTo list

@autopulated One quick check -  Is this true (taken from yotta docs) for inherited targets ? This targets inherits from mbed-gcc which defines similarTo - gcc and mbed. Do we need to specify this again for this target? I would say no, therefore this can be closed, and gcc similarTo defined in this target to be removed

**Comment by autopulated** [comment] 2015-11-09 10:15
It should be inherited, if that isn't working it's a bug – could you confirm?

**Comment by 0xc0170** [comment] 2015-11-09 13:00
@markus-becker-tridonic-com Please can you test again now and update this issue or close it? I have been using F429, had not problems with cmsis.

**Comment by markus-becker-tridonic-com** [comment] 2015-11-12 15:54
Still present:

```
-- Generating done
-- Build files have been written to: C:/Users/Markus.Becker/GitRepos/mbed/examples/mbed-client-example-6lowpan-f429-updated/build/stm32f429i-disco-gcc
[1/319] Building C object ym/dlmalloc/source/CMakeFiles/dlmalloc.dir/6f351a5ed1f9ee45f8cc3bb7d6a355cb/yotta_modules/dlmalloc/source/dlmalloc.c.o
[2/319] Building C object ym/compiler-polyfill/yotta_dummy_lib_compiler_polyfill/CMakeFiles/compiler-polyfill.dir/dummy.c.o
[3/319] Building C object ym/nanostack-libservice/source/CMakeFiles/nanostack-libservice.dir/0ff66fd216af7f8d752a45e71556b350/source/libip6string/stoip6.c.o
[4/319] Building C object ym/nanostack-libservice/source/CMakeFiles/nanostack-libservice.dir/0ff66fd216af7f8d752a45e71556b350/source/nsdynmemLIB/nsdynmemLIB.c.o
[5/319] Building C object ym/nanostack-libservice/source/CMakeFiles/nanostack-libservice.dir/0ff66fd216af7f8d752a45e71556b350/source/libTrace/ns_trace.c.o
[6/319] Building C object ym/nanostack-libservice/source/CMakeFiles/nanostack-libservice.dir/0ff66fd216af7f8d752a45e71556b350/source/IPv6_fcf_lib/ip_fsc.c.o
[7/319] Linking C static library ym/compiler-polyfill/yotta_dummy_lib_compiler_polyfill/compiler-polyfill.a
C:/Users/Markus.Becker/GitRepos/mbed/examples/mbed-client-example-6lowpan-f429-updated/yotta_modules/nanostack-libservice/source/libip6string/stoip6.c: In function 'stoip6':
C:/Users/Markus.Becker/GitRepos/mbed/examples/mbed-client-example-6lowpan-f429-updated/yotta_modules/nanostack-libservice/source/libip6string/stoip6.c:44:42: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (field_no = 0, p = ip6addr; (len > (p - ip6addr)) && *p && field_no < 8; p = q + 1) {
                                          ^
C:/Users/Markus.Becker/GitRepos/mbed/examples/mbed-client-example-6lowpan-f429-updated/yotta_modules/nanostack-libservice/source/libip6string/stoip6.c:54:18: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if ((len > (q - ip6addr)) && *q && (q[0] == ':') && (q[1] == ':')) {
                  ^
[8/319] Building C object ym/nanostack-libservice/source/CMakeFiles/nanostack-libservice.dir/0ff66fd216af7f8d752a45e71556b350/source/libBits/common_functions.c.o
[9/319] Building C object ym/nanostack-libservice/source/CMakeFiles/nanostack-libservice.dir/0ff66fd216af7f8d752a45e71556b350/source/libList/ns_list.c.o
[10/319] Building C object ym/nanostack-libservice/source/CMakeFiles/nanostack-libservice.dir/0ff66fd216af7f8d752a45e71556b350/source/libip6string/ip6tos.c.o
[11/319] Building ASM object ym/uvisor-lib/source/CMakeFiles/uvisor-lib.dir/STM32F429xx/uvisor-GCC_ARM.s.obj
[12/319] Building CXX object ym/uvisor-lib/source/CMakeFiles/uvisor-lib.dir/error.cpp.o
[13/319] Building CXX object ym/uvisor-lib/source/CMakeFiles/uvisor-lib.dir/interrupts.cpp.o
[14/319] Building CXX object ym/uvisor-lib/source/CMakeFiles/uvisor-lib.dir/benchmark.cpp.o
[15/319] Building CXX object ym/sal/source/CMakeFiles/sal.dir/6f351a5ed1f9ee45f8cc3bb7d6a355cb/yotta_modules/sal/source/test/socket_abstract_test.cpp.o
FAILED: C:\winapps\Eclipse_Toolchain\GNU_Tools_ARM_Embedded\4.9_2015q1\bin\arm-none-eabi-g++.exe   -fno-exceptions -fno-unwind-tables -ffunction-sections -fdata-sections -Wall -Wextra -fno-rtti -fno-threadsafe-statics -mcpu=cortex-m4 -mthumb -D__thumb2__ -Os -g -gdwarf-3 -DNDEBUG -Igenerated/include -IC:/Users/Markus.Becker/GitRepos/mbed/examples/mbed-client-example-6lowpan-f429-updated -IC:/Users/Markus.Becker/GitRepos/mbed/examples/mbed-client-example-6lowpan-f429-updated/yotta_modules/mbed-client -IC:/Users/Markus.Becker/GitRepos/mbed/examples/mbed-client-example-6lowpan-f429-updated/yotta_modules/atmel-rf-driver -IC:/Users/Markus.Becker/GitRepos/mbed/examples/mbed-client-example-6lowpan-f429-updated/yotta_modules/mbed-mesh-api -IC:/Users/Markus.Becker/GitRepos/mbed/examples/mbed-client-example-6lowpan-f429-updated/yotta_modules/mbed-client-c -IC:/Users/Markus.Becker/GitRepos/mbed/examples/mbed-client-example-6lowpan-f429-updated/yotta_modules/mbed-client-mbed-os -IC:/Users/Markus.Becker/GitRepos/mbed/examples/mbed-client-example-6lowpan-f429-updated/yotta_modules/mbed-client-mbedtls -IC:/Users/Markus.Becker/GitRepos/mbed/examples/mbed-client-example-6lowpan-f429-updated/yotta_modules/nanostack-libservice -IC:/Users/Markus.Becker/GitRepos/mbed/examples/mbed-client-example-6lowpan-f429-updated/yotta_modules/mbed-drivers -IC:/Users/Markus.Becker/GitRepos/mbed/examples/mbed-client-example-6lowpan-f429-updated/yotta_modules/sockets -IC:/Users/Markus.Becker/GitRepos/mbed/examples/mbed-client-example-6lowpan-f429-updated/yotta_modules/mbed-hal -IC:/Users/Markus.Becker/GitRepos/mbed/examples/mbed-client-example-6lowpan-f429-updated/yotta_modules/cmsis-core -IC:/Users/Markus.Becker/GitRepos/mbed/examples/mbed-client-example-6lowpan-f429-updated/yotta_modules/ualloc -IC:/Users/Markus.Becker/GitRepos/mbed/examples/mbed-client-example-6lowpan-f429-updated/yotta_modules/minar -IC:/Users/Markus.Becker/GitRepos/mbed/examples/mbed-client-example-6lowpan-f429-updated/yotta_modules/core-util -IC:/Users/Markus.Becker/GitRepos/mbed/examples/mbed-client-example-6lowpan-f429-updated/yotta_modules/mbed-hal-st -IC:/Users/Markus.Becker/GitRepos/mbed/examples/mbed-client-example-6lowpan-f429-updated/yotta_modules/mbed-hal-st-stm32f4 -IC:/Users/Markus.Becker/GitRepos/mbed/examples/mbed-client-example-6lowpan-f429-updated/yotta_modules/uvisor-lib -IC:/Users/Markus.Becker/GitRepos/mbed/examples/mbed-client-example-6lowpan-f429-updated/yotta_modules/mbed-hal-st-stm32cubef4 -IC:/Users/Markus.Becker/GitRepos/mbed/examples/mbed-client-example-6lowpan-f429-updated/yotta_modules/mbed-hal-st-stm32f429zi -IC:/Users/Markus.Becker/GitRepos/mbed/examples/mbed-client-example-6lowpan-f429-updated/yotta_modules/cmsis-core-st -IC:/Users/Markus.Becker/GitRepos/mbed/examples/mbed-client-example-6lowpan-f429-updated/yotta_modules/cmsis-core-stm32f4 -IC:/Users/Markus.Becker/GitRepos/mbed/examples/mbed-client-example-6lowpan-f429-updated/yotta_modules/cmsis-core-stm32f429xi -IC:/Users/Markus.Becker/GitRepos/mbed/examples/mbed-client-example-6lowpan-f429-updated/yotta_modules/dlmalloc -IC:/Users/Markus.Becker/GitRepos/mbed/examples/mbed-client-example-6lowpan-f429-updated/yotta_modules/compiler-polyfill -IC:/Users/Markus.Becker/GitRepos/mbed/examples/mbed-client-example-6lowpan-f429-updated/yotta_modules/minar-platform -IC:/Users/Markus.Becker/GitRepos/mbed/examples/mbed-client-example-6lowpan-f429-updated/yotta_modules/minar-platform-mbed -IC:/Users/Markus.Becker/GitRepos/mbed/examples/mbed-client-example-6lowpan-f429-updated/yotta_modules/sal -IC:/Users/Markus.Becker/GitRepos/mbed/examples/mbed-client-example-6lowpan-f429-updated/yotta_modules/mbedtls -IC:/Users/Markus.Becker/GitRepos/mbed/examples/mbed-client-example-6lowpan-f429-updated/yotta_modules/sal-stack-nanostack -IC:/Users/Markus.Becker/GitRepos/mbed/examples/mbed-client-example-6lowpan-f429-updated/yotta_modules/sal-stack-nanostack-eventloop -IC:/Users/Markus.Becker/GitRepos/mbed/examples/mbed-client-example-6lowpan-f429-updated/yotta_modules/nanostack-randlib -IC:/Users/Markus.Becker/GitRepos/mbed/examples/mbed-client-example-6lowpan-f429-updated/yotta_modules/mbed-6lowpan-eventloop-adaptor -IC:/Users/Markus.Becker/GitRepos/mbed/examples/mbed-client-example-6lowpan-f429-updated/yotta_modules/sal-iface-6lowpan -IC:/Users/Markus.Becker/GitRepos/mbed/examples/mbed-client-example-6lowpan-f429-updated/yotta_modules/sal/source    -DTOOLCHAIN_GCC -DTOOLCHAIN_GCC_ARM -DMBED_OPERATORS -DTARGET_STM32F429I_DISCO -DTARGET_STM32F429ZI -DTARGET_STM32F4 -DTOOLCHAIN_GCC -DTOOLCHAIN_GCC_ARM -include "C:/Users/Markus.Becker/GitRepos/mbed/examples/mbed-client-example-6lowpan-f429-updated/build/stm32f429i-disco-gcc/yotta_config.h" -MMD -MT ym/sal/source/CMakeFiles/sal.dir/6f351a5ed1f9ee45f8cc3bb7d6a355cb/yotta_modules/sal/source/test/socket_abstract_test.cpp.o -MF ym/sal/source/CMakeFiles/sal.dir/6f351a5ed1f9ee45f8cc3bb7d6a355cb/yotta_modules/sal/source/test/socket_abstract_test.cpp.o.d -o ym/sal/source/CMakeFiles/sal.dir/6f351a5ed1f9ee45f8cc3bb7d6a355cb/yotta_modules/sal/source/test/socket_abstract_test.cpp.o -c C:/Users/Markus.Becker/GitRepos/mbed/examples/mbed-client-example-6lowpan-f429-updated/yotta_modules/sal/source/test/socket_abstract_test.cpp
In file included from C:/Users/Markus.Becker/GitRepos/mbed/examples/mbed-client-example-6lowpan-f429-updated/yotta_modules/sal/source/test/socket_abstract_test.cpp:19:0:
C:/Users/Markus.Becker/GitRepos/mbed/examples/mbed-client-example-6lowpan-f429-updated/yotta_modules/sal/mbed-net-socket-abstract/socket_api.h:95:19: fatal error: cmsis.h: No such file or directory
 #include "cmsis.h"
                   ^
compilation terminated.
ninja: build stopped: subcommand failed.
error: command ['ninja'] failed

```

**Comment by markus-becker-tridonic-com** [comment] 2015-11-12 15:56
More details:
This is in mbed-client-example-6lowpan

**Comment by autopulated** [comment] 2015-11-12 17:36
Thanks, I'm opening an issue on yotta to track this: https://github.com/ARMmbed/yotta/issues/570

**Comment by autopulated** [comment] 2015-11-13 10:16
I've been able to confirm that the `mbed` value is inherited correctly and is not the cause of this.

After fixing the pins used in various files (which were K64F specific) and the entropy source in mbedtls (also K64F specific), mbed-client-example-6lowpan builds successfully for me using this target.

Could you check that all your dependencies are up to date? (The output of `yotta ls -a` would be useful in diagnosing your problem)

**Comment by markus-becker-tridonic-com** [comment] 2015-12-01 16:55
Are the pin fixes and entropy fixes commited? I have done them as well locally, but it would be good, if this would would work right out-of-the-box.

**Comment by autopulated** [comment] 2015-12-01 17:31
They aren't – my "fixes" were just quick ones to get things compiling, not necessarily the right ones. The best thing to do is to open issues on the repositories concerned, so that they get tracked properly.

Thanks for bumping this!

**Comment by 0xc0170** [comment] 2015-12-02 07:53
@markus-becker-tridonic-com Is this issue still present? If not, please close.

**Comment by markus-becker-tridonic-com** [comment] 2015-12-10 13:04
I think it would make sense to have the "fixes" in. I opened a ticket on mbedtls: https://github.com/ARMmbed/mbedtls/issues/369. Was there another fix required?

**Closed** 2016-04-22 07:10 UTC
Labels: mirrored
